import React, { useState } from "react";
import { Lightbulb, Check, HelpCircle, User, Sparkles, RefreshCw, Send, ShieldCheck } from "lucide-react";
import { Recommendation } from "../types";

interface RecommendationsTabProps {
  recommendations: Recommendation[];
  selectedDatasetId: string;
  onUpdateStatus: (id: string, status: string, assignedTo?: string) => Promise<void>;
  onGenerateAiRecommendations: (datasetId: string) => Promise<void>;
}

export default function RecommendationsTab({
  recommendations,
  selectedDatasetId,
  onUpdateStatus,
  onGenerateAiRecommendations,
}: RecommendationsTabProps) {
  const [loadingId, setLoadingId] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [assigneeInputs, setAssigneeInputs] = useState<{ [key: string]: string }>({});

  const filteredRecs = recommendations;

  const handleStatusChange = async (id: string, status: string, assignedTo?: string) => {
    try {
      setLoadingId(id);
      await onUpdateStatus(id, status, assignedTo);
    } catch (e) {
      console.error(e);
    } finally {
      setLoadingId(null);
    }
  };

  const handleGenerateClick = async () => {
    if (!selectedDatasetId) return;
    try {
      setGenerating(true);
      await onGenerateAiRecommendations(selectedDatasetId);
    } catch (e) {
      console.error(e);
    } finally {
      setGenerating(false);
    }
  };

  const getPriorityClass = (priority: string) => {
    switch (priority) {
      case "High":
        return "text-red-400 bg-red-500/10 border-red-500/20";
      case "Medium":
        return "text-amber-400 bg-amber-500/10 border-amber-500/20";
      default:
        return "text-emerald-400 bg-emerald-500/10 border-emerald-500/20";
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "Completed":
        return "text-emerald-400 border-emerald-500/20 bg-emerald-500/5";
      case "In_Progress":
        return "text-cyan-400 border-cyan-500/20 bg-cyan-500/5";
      case "Approved":
        return "text-blue-400 border-blue-500/20 bg-blue-500/5";
      case "Dismissed":
        return "text-slate-500 border-slate-800 bg-slate-900";
      default:
        return "text-amber-400 border-amber-500/20 bg-amber-500/5";
    }
  };

  return (
    <div className="space-y-6">
      {/* Top Advisory bar with trigger */}
      <div className="flex flex-col gap-4 rounded-xl glass-panel p-5 sm:flex-row sm:items-center sm:justify-between animate-fade-in">
        <div className="flex items-center gap-3">
          <div className="flex h-11 w-11 items-center justify-center rounded-lg bg-slate-950/40 border border-white/5 text-cyan-400 backdrop-blur-sm">
            <Lightbulb className="h-5.5 w-5.5 animate-pulse" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white font-display">Actionable Decision Intelligence Engine</h3>
            <p className="text-[11px] text-slate-400 mt-1">
              Active community operational recommendations generated by Gemini in-context reasoning.
            </p>
          </div>
        </div>

        {selectedDatasetId && (
          <button
            onClick={handleGenerateClick}
            disabled={generating}
            className="flex items-center gap-1.5 rounded-lg bg-gradient-to-r from-cyan-500 to-emerald-500 px-4 py-2 text-xs font-bold text-slate-950 hover:opacity-95 hover:scale-[1.02] active:scale-[0.98] transition-all cursor-pointer shadow-md border border-white/10 font-display"
          >
            {generating ? <RefreshCw className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4 animate-pulse" />}
            <span>Consult Gemini AI Recommendations</span>
          </button>
        )}
      </div>

      {/* Grid List */}
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        {filteredRecs.length === 0 ? (
          <div className="rounded-xl border border-dashed border-white/10 p-12 text-center lg:col-span-2 backdrop-blur-sm">
            <Lightbulb className="mx-auto h-8 w-8 text-slate-500 animate-pulse" />
            <p className="mt-3 text-xs text-slate-400 font-display">No active operational recommendation. Click generate above.</p>
          </div>
        ) : (
          filteredRecs.map((rec) => (
            <div
              key={rec.id}
              className="flex flex-col justify-between rounded-xl glass-panel p-5 glass-panel-hover"
            >
              {/* Card Upper */}
              <div>
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-2">
                    <span className={`rounded-md border px-2 py-0.5 text-[9px] font-bold uppercase font-display ${getPriorityClass(rec.priority)}`}>
                      {rec.priority} Priority
                    </span>
                    <span className="rounded-md border px-2 py-0.5 text-[9px] font-bold uppercase bg-slate-950/40 text-slate-400 border-white/5">
                      AI Confidence: {rec.confidence}%
                    </span>
                  </div>

                  <span className={`rounded-md border px-2 py-0.5 text-[9px] font-bold uppercase font-display ${getStatusBadge(rec.status)}`}>
                    {rec.status.replace("_", " ")}
                  </span>
                </div>

                <h4 className="mt-3 text-sm font-bold text-white font-display">{rec.title}</h4>
                <p className="text-[11px] text-slate-400 mt-1 leading-relaxed">{rec.description}</p>

                {/* Subsections: Impact vs Benefit */}
                <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
                  <div className="rounded-lg bg-slate-950/40 p-2.5 border border-white/5 backdrop-blur-sm">
                    <p className="text-[9px] font-bold uppercase text-slate-500 font-display">Operational Impact</p>
                    <p className="text-[10px] text-slate-350 mt-0.5 leading-normal">{rec.impact}</p>
                  </div>
                  <div className="rounded-lg bg-slate-950/40 p-2.5 border border-white/5 backdrop-blur-sm">
                    <p className="text-[9px] font-bold uppercase text-slate-500 font-display">Estimated Benefit</p>
                    <p className="text-[10px] text-slate-350 mt-0.5 leading-normal">{rec.benefit}</p>
                  </div>
                </div>
              </div>

              {/* Card Lower (Assignee & Actions) */}
              <div className="mt-5 border-t border-white/5 pt-4 flex flex-col gap-3">
                {/* Assignee display/input */}
                <div className="flex items-center justify-between text-xs">
                  <div className="flex items-center gap-1.5 text-slate-400">
                    <User className="h-4 w-4" />
                    <span>Assignee Task:</span>
                    <span className="text-white font-semibold font-display">
                      {rec.assignedTo || "Unassigned"}
                    </span>
                  </div>

                  {rec.status !== "Completed" && (
                    <div className="flex items-center gap-1.5">
                      <input
                        type="text"
                        placeholder="Assign Official..."
                        value={assigneeInputs[rec.id] || ""}
                        onChange={(e) => setAssigneeInputs({ ...assigneeInputs, [rec.id]: e.target.value })}
                        className="rounded-lg glass-input px-2.5 py-1 text-[10px] text-slate-200 focus:outline-none"
                      />
                      <button
                        onClick={() => {
                          const val = assigneeInputs[rec.id];
                          if (val) {
                            handleStatusChange(rec.id, "In_Progress", val);
                            setAssigneeInputs({ ...assigneeInputs, [rec.id]: "" });
                          }
                        }}
                        className="rounded-lg bg-cyan-500 p-1.5 text-slate-950 hover:opacity-90 active:scale-95 transition-all cursor-pointer"
                        title="Update Assignee & Begin Dispatch"
                      >
                        <Send className="h-3 w-3" />
                      </button>
                    </div>
                  )}
                </div>

                {/* Workflow Buttons */}
                <div className="flex items-center gap-2 mt-1">
                  {rec.status === "Pending" && (
                    <button
                      onClick={() => handleStatusChange(rec.id, "Approved")}
                      disabled={loadingId === rec.id}
                      className="flex-1 rounded-lg bg-blue-500/10 border border-blue-500/25 py-1.5 text-center text-[10px] font-bold text-blue-400 hover:bg-blue-500/20 transition-all cursor-pointer font-display"
                    >
                      Approve Proposal
                    </button>
                  )}

                  {rec.status === "Approved" && (
                    <button
                      onClick={() => handleStatusChange(rec.id, "In_Progress", "Dispatch Commander")}
                      disabled={loadingId === rec.id}
                      className="flex-1 rounded-lg bg-cyan-500/10 border border-cyan-500/25 py-1.5 text-center text-[10px] font-bold text-cyan-400 hover:bg-cyan-500/20 transition-all cursor-pointer font-display"
                    >
                      Begin Dispatch Route
                    </button>
                  )}

                  {rec.status === "In_Progress" && (
                    <button
                      onClick={() => handleStatusChange(rec.id, "Completed")}
                      disabled={loadingId === rec.id}
                      className="flex-1 rounded-lg bg-emerald-500/10 border border-emerald-500/25 py-1.5 text-center text-[10px] font-bold text-emerald-400 hover:bg-emerald-500/20 flex items-center justify-center gap-1 transition-all cursor-pointer font-display"
                    >
                      <ShieldCheck className="h-3.5 w-3.5" />
                      <span>Complete Work Order</span>
                    </button>
                  )}

                  {rec.status !== "Completed" && rec.status !== "Dismissed" && (
                    <button
                      onClick={() => handleStatusChange(rec.id, "Dismissed")}
                      disabled={loadingId === rec.id}
                      className="rounded-lg border border-white/10 bg-slate-950/40 px-3 py-1.5 text-[10px] font-medium text-slate-400 hover:text-white hover:bg-slate-950/60 transition-all cursor-pointer font-display"
                    >
                      Dismiss
                    </button>
                  )}
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
